### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by psamim** [warp-plus/warpy#3]
Hi,
Can you also provide usage?
I did this, am I correct?

- Copy the displayed config in to `/etc/wireguard/client.conf`
- Start by `wg-quick up client`

Thanks for sharing this

**Comment by Dragon-Born** [comment]
@psamim
Yes that's right.

It's very simple if you're using Windows or macOS, open the WireGuard GUI and click on 
> Add Tunnel -> Add empty tunnel 

and paste the whole displayed config there.

If you're on GNU/Linux create the `/etc/wireguard/wg0.conf` file with the following contents:
```
[Interface]
PrivateKey = <your private key here>
Address = 172.16.0.2
DNS = 1.1.1.1
[Peer]
PublicKey = <your public key here>
Endpoint = engage.cloudflareclient.com:2408
AllowedIPs = 0.0.0.0/0
```
make sure your config file has the right permissions:
```
chmod 600 /etc/wireguard/wg0.conf
```
Now you can activate the `wg0` interface on your client device using the `sudo wg-quick up wg0` command.
